<?php
include("fpdf.php");
$pdf=new FPDF();
$pdf->Open();
$pdf->AddPage('P', 'A5');
$pdf->AddFont('arial_ce','','arial_ce.php');
$pdf->AddFont('arial_ce','I','arial_ce_i.php');
$pdf->AddFont('arial_ce','B','arial_ce_b.php');
$pdf->AddFont('arial_ce','BI','arial_ce_bi.php');
$pdf -> SetFont('arial_ce', 'B',  20);
$pdf -> SetXY(10, 15);
$pdf -> SetFont('arial_ce', 'BI',  35);
$pdf -> SetTextColor(255, 0, 0);
$x = $pdf->GetX();
$y = $pdf->GetY();
$pdf->SetXY($x, $y+2);
$pdf->MultiCell(90,15, 'Formularz aplikacyjny:', 0, 'L', 0);
$pdf -> SetFont('arial_ce', 'BI',  13);
$pdf -> SetTextColor(0, 0, 0);
$x = $pdf->GetX();
$y = $pdf->GetY();
$pdf->SetXY($x, $y+8);
$imiee= iconv('utf-8','windows-1250//TRANSLIT', 'imię:');
$pdf->MultiCell(100,1, $imiee, '0', 'L', 0);
$pdf -> SetFont('arial_ce', 'B',  15);
$pdf -> SetTextColor(0, 0, 0);
$x = $pdf->GetX();
$y = $pdf->GetY();
$pdf->SetXY($x, $y+4);
$imie= iconv('utf-8','windows-1250//TRANSLIT', $_POST['imiee']);
$pdf->MultiCell(100,7, $imie, 0, 'L', 0);
$pdf -> SetFont('arial_ce', 'BI',  13);
$pdf -> SetTextColor(0, 0, 0);
$x = $pdf->GetX();
$y = $pdf->GetY();
$pdf->SetXY($x, $y+5);
$pdf->MultiCell(100,1, 'nazwisko:', 0, 'L', 0);
$pdf -> SetFont('arial_ce', 'B',  15);
$pdf -> SetTextColor(0, 0, 0);
$x = $pdf->GetX();
$y = $pdf->GetY();
$pdf->SetXY($x, $y+4);
$nazwisko = iconv('utf-8','windows-1250//TRANSLIT', $_POST['nazwiskoo']);
$pdf->MultiCell(100,7, $nazwisko, 0, 'L', 0);
$pdf -> SetFont('arial_ce', 'BI',  13);
$pdf -> SetTextColor(0, 0, 0);
$x = $pdf->GetX();
$y = $pdf->GetY();
$pdf->SetXY($x, $y+5);
$pdf->MultiCell(100,1, 'numer albumu:', 0, 'L', 0);
$pdf -> SetFont('arial_ce', 'B',  15);
$pdf -> SetTextColor(0, 0, 0);
$x = $pdf->GetX();
$y = $pdf->GetY();
$pdf->SetXY($x, $y+4);
$NR_albumu = iconv('utf-8','windows-1250//TRANSLIT', $_POST['NR_albumuu']);
$pdf->MultiCell(100,7, $NR_albumu, 0, 'L', 0);
$pdf -> SetFont('arial_ce', 'BI',  13);
$pdf -> SetTextColor(0, 0, 0);
$x = $pdf->GetX();
$y = $pdf->GetY();
$pdf->SetXY($x, $y+5);
$pdf->MultiCell(100,1, 'semestr:', 0, 'L', 0);
$pdf -> SetFont('arial_ce', 'B',  15);
$pdf -> SetTextColor(0, 0, 0);
$x = $pdf->GetX();
$y = $pdf->GetY();
$pdf->SetXY($x, $y+4);
$semestr= iconv('utf-8','windows-1250//TRANSLIT', $_POST['semestrr']);
$pdf->MultiCell(100,7, $semestr, 0, 'L', 0);
$pdf -> SetFont('arial_ce', 'BI',  13);
$pdf -> SetTextColor(0, 0, 0);
$x = $pdf->GetX();
$y = $pdf->GetY();
$pdf->SetXY($x, $y+5);
$pdf->MultiCell(100,1, 'kierunek:', 0, 'L', 0);
$pdf -> SetFont('arial_ce', 'B',  15);
$pdf -> SetTextColor(0, 0, 0);
$x = $pdf->GetX();
$y = $pdf->GetY();
$pdf->SetXY($x, $y+4);
$kierunek= iconv('utf-8','windows-1250//TRANSLIT', $_POST['kierunekk']);
$pdf->MultiCell(100,7, $kierunek, 0, 'L', 0);
$pdf -> SetFont('arial_ce', 'BI',  13);
$pdf -> SetTextColor(0, 0, 0);
$x = $pdf->GetX();
$y = $pdf->GetY();
$pdf->SetXY($x, $y+5);
$stop= iconv('utf-8','windows-1250//TRANSLIT', 'stopień:');
$pdf->MultiCell(100,1, $stop, 0, 'L', 0);
$pdf -> SetFont('arial_ce', 'B',  15);
$pdf -> SetTextColor(0, 0, 0);
$x = $pdf->GetX();
$y = $pdf->GetY();
$pdf->SetXY($x, $y+4);
$stopien= iconv('utf-8','windows-1250//TRANSLIT', $_POST['stopienn']);
$pdf->MultiCell(100,7, $stopien, 0, 'L', 0);
$pdf -> SetFont('arial_ce', 'BI',  13);
$pdf -> SetTextColor(0, 0, 0);
$x = $pdf->GetX();
$y = $pdf->GetY();
$pdf->SetXY($x, $y+5);
$specj= iconv('utf-8','windows-1250//TRANSLIT', 'specjalność:');
$pdf->MultiCell(100,1, $specj, 0, 'L', 0);
$pdf -> SetFont('arial_ce', 'B',  15);
$pdf -> SetTextColor(0, 0, 0);
$x = $pdf->GetX();
$y = $pdf->GetY();
$pdf->SetXY($x, $y+4);
$specjalnosc= iconv('utf-8','windows-1250//TRANSLIT', $_POST['specjalnosccc']);
$pdf->MultiCell(100,7, $specjalnosc, 0, 'L', 0);
$pdf -> SetFont('arial_ce', 'BI',  13);
$pdf -> SetTextColor(0, 0, 0);
$x = $pdf->GetX();
$y = $pdf->GetY();
$pdf->SetXY($x, $y+5);
$pdf->MultiCell(100,1, 'email:', 0, 'L', 0);
$pdf -> SetFont('arial_ce', 'B',  15);
$pdf -> SetTextColor(0, 0, 0);
$x = $pdf->GetX();
$y = $pdf->GetY();
$pdf->SetXY($x, $y+4);
$email= iconv('utf-8','windows-1250//TRANSLIT', $_POST['emaill']);
$pdf->MultiCell(100,7, $email, 0, 'L', 0);
$pdf -> SetFont('arial_ce', 'BI',  13);
$pdf -> SetTextColor(0, 0, 0);
$x = $pdf->GetX();
$y = $pdf->GetY();
$pdf->SetXY($x, $y+5);
$sre= iconv('utf-8','windows-1250//TRANSLIT', 'średnia:');
$pdf->MultiCell(100,1, $sre, 0, 'L', 0);
$pdf -> SetFont('arial_ce', 'B',  15);
$pdf -> SetTextColor(0, 0, 0);
$x = $pdf->GetX();
$y = $pdf->GetY();
$pdf->SetXY($x, $y+4);
$srednia= iconv('utf-8','windows-1250//TRANSLIT', $_POST['sredniaa']);
$pdf->MultiCell(100,7, $srednia, 0, 'L', 0);
$pdf -> SetFont('arial_ce', 'BI',  13);
$pdf -> SetTextColor(0, 0, 0);
$x = $pdf->GetX();
$y = $pdf->GetY();
$pdf->SetXY($x, $y+5);
$zai= iconv('utf-8','windows-1250//TRANSLIT', 'zainteresowania i przykładowy temat pracy:');
$pdf->MultiCell(100,1, $zai, 0, 'L', 0);
$pdf -> SetFont('arial_ce', 'B',  15);
$pdf -> SetTextColor(0, 0, 0);
$x = $pdf->GetX();
$y = $pdf->GetY();
$pdf->SetXY($x, $y+4);
$comment= iconv('utf-8','windows-1250//TRANSLIT', $_POST['commentt']);
$pdf->MultiCell(100,7, $comment, 0, 'L', 0);
$pdf -> SetFont('arial_ce', 'BI',  13);
$pdf -> SetTextColor(0, 0, 0);
$x = $pdf->GetX();
$y = $pdf->GetY();
$pdf->SetXY($x, $y+5);
$pdf->MultiCell(100,1, 'wybieram promotora:', 0, 'L', 0);
$pdf -> SetFont('arial_ce', 'B',  15);
$pdf -> SetTextColor(0, 0, 0);
$x = $pdf->GetX();
$y = $pdf->GetY();
$pdf->SetXY($x, $y+4);
$promotor= iconv('utf-8','windows-1250//TRANSLIT', $_POST['proomotor']);
$pdf->MultiCell(100,7, $promotor, 0, 'L', 0);
$pdf -> SetFont('arial_ce', 'BI',  13);
$pdf -> SetTextColor(0, 0, 0);
$x = $pdf->GetX();
$y = $pdf->GetY();
$pdf->SetXY($x, $y+5);
$pdf->MultiCell(100,1, 'wybieram alternatywnego promotora:', 0, 'L', 0);
$pdf -> SetFont('arial_ce', 'B',  15);
$pdf -> SetTextColor(0, 0, 0);
$x = $pdf->GetX();
$y = $pdf->GetY();
$pdf->SetXY($x, $y+4);
$promotorr= iconv('utf-8','windows-1250//TRANSLIT', $_POST['prommotorr']);
$pdf->MultiCell(100,7, $promotorr, 0, 'L', 0);
$pdf->Output();?>